# Generated by Django 5.2.3 on 2025-06-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_num',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='사건 번호'),
        ),
    ]
