# Generated by Django 5.2.2 on 2025-06-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lstat_cd',
            field=models.CharField(max_length=20, null=True, verbose_name='심급'),
        ),
    ]
