# Generated by Django 5.2.2 on 2025-06-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_lstat_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator_name',
            field=models.CharField(blank=True, help_text='사건 생성 시점의 작성자 이름(기록용)', max_length=50, null=True, verbose_name='작성자 이름'),
        ),
    ]
