# Generated by Django 5.2.2 on 2025-06-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='update_at',
            field=models.DateTimeField(verbose_name='수정일'),
        ),
    ]
