# Generated by Django 5.2.2 on 2025-06-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cat_02',
            field=models.CharField(default='미지정', max_length=50, verbose_name='사건 유형(중)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='cat_03',
            field=models.CharField(default='미지정', max_length=50, verbose_name='사건 유형(소)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator_name',
            field=models.CharField(default='미지정', help_text='사건 생성 시점의 작성자 이름(기록용)', max_length=50, verbose_name='작성자 이름'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='lstat_cd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='심급'),
        ),
        migrations.AlterField(
            model_name='event',
            name='org_cd',
            field=models.CharField(default='미지정', max_length=20, verbose_name='담당 부서'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
