# Generated by Django 5.2.2 on 2025-06-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_created_at_alter_event_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='event',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
