# Generated by Django 5.2.1 on 2025-06-05 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_T',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='코드')),
                ('code_label', models.CharField(max_length=50, verbose_name='코드 이름')),
                ('code_desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='코드 설명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('upper_code', models.ForeignKey(blank=True, db_column='upper_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_codes', to='code_t.code_t', verbose_name='상위 코드')),
            ],
            options={
                'verbose_name': '공통 코드',
                'verbose_name_plural': '공통 코드 목록',
                'db_table': 'code_t',
            },
        ),
    ]
